const quoteElement = document.getElementById("quote");
const newQuoteButton = document.getElementById("new-quote");

// Local quote list — works offline!
const quotes = [
"The more you praise and celebrate your life, the more there is in life to celebrate. — Oprah Winfrey",
"You must find the place inside yourself where nothing is impossible. — Deepak Chopra",
"I’m not a businessman, I’m a business, man. — Jay-Z",
"Life is very interesting… in the end, some of your greatest pains become your greatest strengths. — Drew Barrymore",
"Failure is another stepping stone to greatness. — Oprah Winfrey",
"If you're going through hell, keep going. — Winston Churchill",
"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. — Maya Angelou",
"Effort is attractive. — Rihanna",
"Don’t wait for permission to do something creative. — Ava DuVernay",
"Be yourself. People don’t have to like you, and you don’t have to care. — Demi Lovato",
"If you don’t stand for something, you’ll fall for anything. — Malcolm X",
"Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
"I believe that if you’ll just stand up and go, life will open up for you. — Tina Turner",
"Just because you’re struggling doesn’t mean you’re failing. — Emma Watson",
"I don’t have dreams, I have goals. — Harvey Specter (Gabriel Macht)",
"The only thing standing between you and your goal is the story you keep telling yourself. — Jordan Belfort",
"You’re never too old to reinvent yourself. — Madonna",
"Don't settle for what life gives you; make life better and build something. — Ashton Kutcher",
"At the end of the day, we can endure much more than we think we can. — Frida Kahlo",
"I’m a greater believer in luck, and I find the harder I work the more I have of it. — Thomas Jefferson",
"You can’t let success define you. You can’t let failure define you. — Michelle Obama",
"Stay on your hustle and don’t stop till you get it. — Nas",
"Create your own visual style… let it be unique for yourself and yet identifiable for others. — Orson Welles",
"Fear is a choice. — Will Smith",
"I think it’s possible for ordinary people to choose to be extraordinary. — Elon Musk",
"Passion is energy. Feel the power that comes from focusing on what excites you. — Oprah Winfrey",
"Success is not how high you have climbed, but how you make a positive difference to the world. — Roy T. Bennett",
"Whatever you are, be a good one. — Abraham Lincoln",
"You’re only given a little spark of madness. You mustn’t lose it. — Robin Williams",
"If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is. — Angelina Jolie",
"I work hard for the audience. It’s entertainment. I don’t need validation. — Lady Gaga",
"You’ve got to learn to leave the table when love’s no longer being served. — Nina Simone",
"Never let the fear of striking out keep you from playing the game. — Hilary Duff",
"Don’t be afraid to speak up for yourself. Keep fighting for your dreams! — Gabby Douglas",
"Success is peace of mind, which is a direct result of self-satisfaction. — John Wooden",
"Stop shrinking to fit places you’ve outgrown. — Oprah Winfrey",
"The minute you learn to love yourself, you won’t want to be anyone else. — Rihanna",
"You can’t move mountains by whispering at them. — Pink",
"Think big. Dream bigger. — Stephen Curry",
"It’s not about being the best. It’s about being better than you were yesterday. — Floyd Mayweather",
"Work hard, be kind, and amazing things will happen. — Conan O’Brien",
"You have to be odd to be number one. — Dr. Seuss",
"Don’t be afraid to be ambitious. — Arnold Schwarzenegger",
"Life is tough, but so are you. — Demi Lovato",
"The best way to guarantee a loss is to quit. — Morgan Freeman",
"I wake up every morning believing today is going to be better than yesterday. — Will Smith",
"Sometimes, things may not go your way, but the effort should be there every single night. — Michael Jordan",
"The world is yours if you hustle. — Cardi B",
"The most powerful thing you can be is yourself. — Dwayne Johnson",
"Success isn’t about the end result, it’s about what you learn along the way. — Vera Wang",
"The worst enemy to creativity is self-doubt. — Sylvia Plath",
"Confidence comes from hours and days and weeks and years of constant work and dedication. — Robert Downey Jr.",
"I don’t believe in luck. I believe in hard work. — Simone Biles",
"Your legacy is being written by yourself. Make the right decisions. — Gary Vaynerchuk",
"One good thing about music, when it hits you, you feel no pain. — Bob Marley",
"You can’t put a limit on anything. The more you dream, the farther you get. — Michael Phelps",
"When you’re passionate, you’ll find ways to make it happen. — Taylor Swift",
"Be thankful for what you have; you’ll end up having more. — Oprah Winfrey",
"The greatest thing you’ll ever learn is just to love and be loved in return. — Eden Ahbez",
"If you want to be great, stop asking for permission. — Kobe Bryant",
"Success doesn’t rush. The greatest reward is the journey. — Jeff Bezos",
"Let your smile change the world, but don’t let the world change your smile. — Connor Franta",
"Smile and let everyone know that today, you’re a lot stronger than you were yesterday. — Drake",
"If you obey all the rules, you miss all the fun. — Katharine Hepburn",
"Don’t wait. The time will never be just right. — Napoleon Hill",
"You are never too small to make a difference. — Greta Thunberg",
"It takes a lot of courage to show your dreams to someone else. — Erma Bombeck",
"Change the game, don’t let the game change you. — Macklemore",
"Be so good they can’t ignore you. — Steve Martin",
"I say if I’m beautiful. I say if I’m strong. You will not determine my story—I will. — Amy Schumer",
"You have to believe in yourself when no one else does. — Serena Williams",
"Chase your dreams, but always know the road that will lead you home again. — Tim McGraw",
"It always protects, always trusts, always hopes, always perseveres. — 1 Corinthians 13:7 (quoted by Justin Bieber)",
"When you feel like quitting, think about why you started. — Shawn Mendes",
"Everything happens for a reason. — Britney Spears",
"Success is the best revenge. — Kanye West",
"Let the haters be your motivators. — Nicki Minaj",
"To me, fearless is not the absence of fear. It’s not being completely unafraid. — Taylor Swift",
"I may be a beginner at some things, but I’ve got a black belt in dreaming. — Priyanka Chopra",
"Be loud about the things that are important to you. — Karen Walrond",
"You don’t have to control your thoughts; you just have to stop letting them control you. — Dan Millman",
"I’d rather regret the risks that didn’t work out than the chances I didn’t take at all. — Simone Biles",
"Energy is contagious. Either you affect people or you infect people. — T.D. Jakes",
"Make your life a masterpiece; imagine no limitations on what you can be, have or do. — Brian Tracy",
"One day or day one. You decide. — Chris Pratt",
"Be the type of person you want to meet. — Tom Hiddleston",
"It takes courage to grow up and become who you really are. — E.E. Cummings",
"Keep your eyes on the stars, and your feet on the ground. — Theodore Roosevelt",
"Love yourself first, because that’s who you’ll be spending the rest of your life with. — Tyra Banks",
"Just keep swimming. — Dory (Ellen DeGeneres)",
"A little progress each day adds up to big results. — Will Ferrell",
"Sometimes you gotta run before you can walk. — Tony Stark (Robert Downey Jr.)",
"The difference between winning and losing is most often not quitting. — Walt Disney",
"Believe in your flyness, conquer your shyness. — Kanye West",
"It’s never too late to be what you might have been. — George Eliot",
"Turn your wounds into wisdom. — Oprah Winfrey",
"The only way to do great work is to love what you do. — Steve Jobs",
"Success isn’t about how much money you make; it’s about the difference you make in people’s lives. — Michelle Obama",
"Fear is stupid. So are regrets. — Marilyn Monroe",
"Nothing is impossible. The word itself says ‘I’m possible!’ — Audrey Hepburn",
"Be yourself; everyone else is already taken. — Oscar Wilde",
"I’m not afraid of storms, for I’m learning how to sail my ship. — Louisa May Alcott",
"The way to get started is to quit talking and begin doing. — Walt Disney",
"I don’t dream at night, I dream all day; I dream for a living. — Steven Spielberg",
"Your time is limited, so don’t waste it living someone else’s life. — Steve Jobs",
"I have not failed. I’ve just found 10,000 ways that won’t work. — Thomas Edison",
"It’s not whether you get knocked down, it’s whether you get up. — Vince Lombardi",
"Some people want it to happen, some wish it would happen, others make it happen. — Michael Jordan",
"You have to believe in yourself when no one else does. — Serena Williams",
"The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey",
"Champions keep playing until they get it right. — Billie Jean King",
"If you want to fly, you have to give up the things that weigh you down. — Toni Morrison",
"Stay true to yourself and never let what somebody else says distract you from your goals. — Michelle Obama",
"Perseverance is failing 19 times and succeeding the 20th. — Julie Andrews",
"You can’t be that kid standing at the top of the slide, overthinking it. You have to go down the chute. — Tina Fey",
"It’s fine to celebrate success, but it is more important to heed the lessons of failure. — Bill Gates",
"Everything negative — pressure, challenges — is all an opportunity for me to rise. — Kobe Bryant",
"Embrace what makes you different. — Priyanka Chopra",
"The more you know who you are and what you want, the less you let things upset you. — Scarlett Johansson",
"If you’re always trying to be normal, you will never know how amazing you can be. — Maya Angelou",
"Don’t let anyone tell you that you can’t do something. — Dwayne ‘The Rock’ Johnson",
"The most effective way to do it, is to do it. — Amelia Earhart",
"Stay hungry, stay foolish. — Steve Jobs",
"The question isn’t who is going to let me; it’s who is going to stop me. — Ayn Rand",
"If you don’t like the road you’re walking, start paving another one. — Dolly Parton",
"I always knew I was going to be rich. I don’t think I ever doubted it for a minute. — Warren Buffett",
"I’m convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance. — Steve Jobs",
"You must do the things you think you cannot do. — Eleanor Roosevelt",
"Being realistic is the most commonly traveled road to mediocrity. — Will Smith",
"Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
"I’ve failed over and over and over again in my life and that is why I succeed. — Michael Jordan",
"Don’t be afraid to give up the good to go for the great. — John D. Rockefeller",
"The biggest risk is not taking any risk. — Mark Zuckerberg",
"You only live once, but if you do it right, once is enough. — Mae West",
"Be the change that you wish to see in the world. — Mahatma Gandhi",
"You can waste your lives drawing lines. Or you can live your life crossing them. — Shonda Rhimes",
"If you have an idea, start today. There’s no better time than now to get going. — Kevin Systrom",
"I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
"Don’t cry because it’s over, smile because it happened. — Dr. Seuss",
"When something is important enough, you do it even if the odds are not in your favor. — Elon Musk",
"To succeed in life, you need two things: ignorance and confidence. — Mark Twain",
"Success is most often achieved by those who don’t know that failure is inevitable. — Coco Chanel",
"The best revenge is massive success. — Frank Sinatra",
"If you want something said, ask a man; if you want something done, ask a woman. — Margaret Thatcher",
"The best thing to hold onto in life is each other. — Audrey Hepburn",
"When you undervalue what you do, the world will undervalue who you are. — Oprah Winfrey",
"I’m not in competition with anyone but myself. — Beyoncé",
"Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. — Marilyn Monroe",
"The formula for success is simple: practice and concentration then more practice and more concentration. — Babe Didrikson Zaharias",
"Do what you feel in your heart to be right – for you’ll be criticized anyway. — Eleanor Roosevelt",
"I like criticism. It makes you strong. — LeBron James",
"A champion is someone who gets up when they can’t. — Jack Dempsey",
"It’s not the load that breaks you down, it’s the way you carry it. — Lena Horne",
"Stay focused. Your start does not determine how you're going to finish. — Herm Edwards",
"Don’t let success go to your head and failure to your heart. — Will Smith",
"The best preparation for tomorrow is doing your best today. — H. Jackson Brown Jr.",
"Never be limited by other people’s limited imaginations. — Dr. Mae Jemison",
"Winning takes precedence over all. There’s no gray area. No almosts. — Kobe Bryant",
"You never really learn much from hearing yourself speak. — George Clooney",
"Love what you do and do what you love. — Ray Bradbury",
"You get in life what you have the courage to ask for. — Oprah Winfrey",
"You must expect great things of yourself before you can do them. — Michael Jordan",
"Be brave. Take risks. Nothing can substitute experience. — Paulo Coelho",
"Think like a queen. A queen is not afraid to fail. Failure is another steppingstone to greatness. — Oprah Winfrey",
"You have to fight to reach your dream. You have to sacrifice and work hard for it. — Lionel Messi",
"If everything was perfect, you would never learn and you would never grow. — Beyoncé",
"I know where I’m going and I know the truth. — Dolly Parton",
"Don’t give it five minutes if you’re not going to give it five years. — Meghan Markle",
"The most courageous act is still to think for yourself. Aloud. — Coco Chanel",
"I don't believe in luck. Luck is preparation meeting opportunity. — Oprah Winfrey",
"Sometimes it’s the smallest decisions that can change your life forever. — Keri Russell",
"Your value doesn’t decrease based on someone’s inability to see your worth. — Emma Watson",
"Work like there is someone working 24 hours a day to take it away from you. — Mark Cuban",
"Success isn’t overnight. It’s when every day you get a little better than the day before. — Dwayne Johnson",
"I don’t like to gamble, but if there’s one thing I’m willing to bet on, it’s myself. — Beyoncé",
"I never dreamed about success. I worked for it. — Estée Lauder",
"If you're not making someone else's life better, you're wasting your time. — Will Smith",
"It always seems impossible until it's done. — Nelson Mandela",
"Hard days are the best because that’s when champions are made. — Gabby Douglas",
"You become what you believe. — Oprah Winfrey",
"I never look back, darling. It distracts from the now. — Edna Mode (Pixar/Brad Bird)",
"The secret of my success is that we have gone to exceptional lengths to hire the best people in the world. — Steve Jobs",
"I’m living my dream and everything else is just a bonus. — Serena Williams",
"Never let the fear of striking out keep you from playing the game. — Babe Ruth",
"I can accept failure, everyone fails at something. But I can't accept not trying. — Michael Jordan",
"Being different isn’t a bad thing. It means you’re brave enough to be yourself. — Luna Lovegood (J.K. Rowling)",
"It takes a lot of courage to show your dreams to someone else. — Erma Bombeck",
"Make bold choices and make mistakes. It's all those things that add up to the person you become. — Angelina Jolie",
"Do the best you can until you know better. Then when you know better, do better. — Maya Angelou",
"Don’t be afraid to be different, be afraid of being the same as everyone else. — Taylor Swift",
"You’re only human. You live once and life is wonderful, so eat the damn red velvet cupcake. — Emma Stone",
"Don’t let anyone ever make you feel like you don’t deserve what you want. — Heath Ledger",
"Keep your head up and your heart strong. — Ben Howard",
"Be fearless in the face of adversity. — Beyoncé",
"You control your destiny — you don’t need magic to do it. — Merida (Brave)",
"Being realistic is the most common path to mediocrity. — Will Smith",
"I always say, the truth doesn’t cost anything, but a lie could cost you everything. — Jennifer Lopez",
"Don’t strive to be perfect. Strive to be authentic. — Idina Menzel",
"If everything was perfect, you would never learn and you would never grow. — Beyoncé",
"The only thing predictable about life is its unpredictability. — Remy (Ratatouille)",
"It’s kind of fun to do the impossible. — Walt Disney",
"Every great dream begins with a dreamer. — Harriet Tubman",
"I knew I was a winner back in the crib. — DJ Khaled",
"Be thankful for what you have; you’ll end up having more. — Oprah Winfrey",
"Keep looking up… that’s the secret of life. — Charlie Brown",
"Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
"I am deliberate and afraid of nothing. — Audre Lorde",
"The dream is free. The hustle is sold separately. — Tyrese Gibson",
"You get what you give. — Jennifer Lopez",
"Confidence is not ‘they will like me.’ Confidence is ‘I’ll be fine if they don’t.’ — Christina Grimmie",
"You have to fight through some bad days to earn the best days of your life. — Zac Efron",
"Why fit in when you were born to stand out? — Dr. Seuss",
"Be a voice, not an echo. — Albert Einstein",
"Keep your heels, head and standards high. — Coco Chanel",
"When you believe in a thing, believe in it all the way. — Walt Disney",
"The most alluring thing a woman can have is confidence. — Beyoncé",
"You have to be unique and different and shine in your own way. — Lady Gaga",
"You can be the lead in your own life. — Kerry Washington",
"I never changed. I just learned. — Selena Gomez",
"Fight for what makes you optimistic about the world. — Bono",
"Don’t apologize for being powerful. — Yara Shahidi",
"You don’t have to be loud to be powerful. — Alexandria Ocasio-Cortez",
"Nothing can dim the light that shines from within. — Maya Angelou",
"You have to be strong and courageous and know that you can do anything you put your mind to. — Rosie Perez",
"Done is better than perfect. — Sheryl Sandberg",
"Don’t let success go to your head or failure to your heart. — Drake",
"Learn from yesterday, live for today, hope for tomorrow. — Albert Einstein",
"Success is a state of mind. If you want success, start thinking of yourself as a success. — Joyce Brothers",
"The time is always right to do what is right. — Martin Luther King Jr.",
"Speak your mind, even if your voice shakes. — Maggie Kuhn",
"A girl should be two things: who and what she wants. — Coco Chanel",
"Your life does not get better by chance, it gets better by change. — Jim Rohn",
"Don't let anyone dull your sparkle. — Marilyn Monroe",
"You miss 100% of the shots you don’t take. — Wayne Gretzky",
"Be bold, be brave enough to be your true self. — Queen Latifah",
"Ignore the critics… only mediocrity is safe from ridicule. — Kevin Costner",
"Never stop doing your best just because someone doesn’t give you credit. — Kamala Harris",
"Turn your face toward the sun and the shadows will fall behind you. — Walt Whitman",
"The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
"I’d rather regret the things I’ve done than regret the things I haven’t done. — Lucille Ball",
"I didn’t come here to be average. — Michael B. Jordan",
"I want every girl to know that her voice can change the world. — Malala Yousafzai",
"Don’t stop until you’re proud. — Serena Williams",
"Think like a proton. Always positive. — Bill Nye",
"The way I see it, if you want the rainbow, you gotta put up with the rain. — Dolly Parton",
"Let your smile be your umbrella. — Pharrell Williams",
"If you want to fly, you have to give up the things that weigh you down. — Toni Morrison",
"I am not afraid of storms for I am learning how to sail my ship. — Louisa May Alcott",
"Be the change you wish to see in the world. — Mahatma Gandhi",
"You’re braver than you believe, and stronger than you seem, and smarter than you think. — A.A. Milne",
"The future belongs to those who prepare for it today. — Malcolm X",
"I want to be remembered as someone who used herself and whatever talents she had to do her work to the very best of her ability. — Ruth Bader Ginsburg",
"Everything you want is on the other side of fear. — Will Smith",
"Do what they think you can’t do. — Drake",
"Just do it. — Nike (endorsed by many athletes)",
"Work hard in silence, let your success be the noise. — Frank Ocean",
"I don’t like to gamble, but if there’s one thing I’m willing to bet on, it’s myself. — Beyoncé",
"It’s not about money or connections — it’s the willingness to outwork and outlearn everyone. — Mark Cuban",
"When people show you who they are, believe them the first time. — Maya Angelou",
"Be kind whenever possible. It is always possible. — Dalai Lama",
"Don’t let yesterday take up too much of today. — Will Rogers",
"You are the CEO of your own life. — Lilly Singh",
"If you don’t like something, change it. If you can’t change it, change your attitude. — Maya Angelou",
"The best way out is always through. — Robert Frost",
"If you want to lift yourself up, lift up someone else. — Booker T. Washington",
"Never let a bad situation bring out the worst in you. — Zendaya",
"You have what it takes to be a victorious, independent, fearless woman. — Tyra Banks",
"Create the highest, grandest vision possible for your life, because you become what you believe. — Oprah Winfrey",
"Push yourself, because no one else is going to do it for you. — LeBron James",
"There is no substitute for hard work. — Thomas Edison",
"Even if you fall on your face, you’re still moving forward. — Denzel Washington",
"Don’t tell people your plans. Show them your results. — Chris Pratt",
"People who are crazy enough to think they can change the world are the ones who do. — Steve Jobs",
"You are your best thing. — Toni Morrison",
"The best revenge is success. — Frank Sinatra",
"You only live once. But if you do it right, once is enough. — Mae West",
"Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
"If you’re not making mistakes, then you’re not making decisions. — Catherine Cook",
"Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
"Be humble. Be hungry. And always be the hardest worker in the room. — Dwayne ‘The Rock’ Johnson",
"To succeed in life, you need two things: ignorance and confidence. — Mark Twain",
"You were born to stand out. Don’t ever try to fit in. — Emma Stone",
"It takes 20 years to make an overnight success. — Eddie Cantor",
"Passion is the genesis of genius. — Tony Robbins",
"You can’t build a reputation on what you are going to do. — Henry Ford",
"Dreams don’t work unless you do. — John C. Maxwell",
"One life. Just one. Why aren’t we running like we’re on fire towards our wildest dreams? — Rumi",
"Don’t bunt. Aim out of the ballpark. — David Ogilvy",
"The only way to achieve greatness is to love what you do. — Steve Ballmer",
"You don’t need everybody to believe in you. Just you. — Russell Simmons",
"Keep taking time for yourself until you’re you again. — Lalah Delia",
"All our dreams can come true, if we have the courage to pursue them. — Walt Disney",
"Be somebody who makes everybody feel like a somebody. — Kid President",
"You can't be brave if you've only had wonderful things happen to you. — Mary Tyler Moore",
"I never dreamed about success, I worked for it. — Estée Lauder",
"Success isn’t about winning, it’s about becoming your best self. — Matthew McConaughey",
"You can start late, look different, be uncertain and still succeed. — Misty Copeland",
"Be so good they have to give you a seat at the table. — Viola Davis",
"You don’t learn to walk by following rules. You learn by doing. — Richard Branson",
"Ambition is the first step to success. — Dwayne Johnson",
"I’m always perpetually out of my comfort zone. — Tory Burch",
"The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
"You can be scared and still do it anyway. — Chrissy Teigen",
"You don’t have to see the whole staircase, just take the first step. — Martin Luther King Jr.",
"The only real mistake is the one from which we learn nothing. — Henry Ford",
"It always seems impossible until it’s done. — Nelson Mandela",
"Don't be afraid to start over. It's a chance to build something better. — Cardi B",
"The best thing you can do is follow your gut. — Ariel Winter",
"I didn’t get there by wishing for it or hoping for it, but by working for it. — Estée Lauder",
"Stay close to anything that makes you glad you are alive. — Halsey",
"Success is the best makeup. — Zendaya",
"Let your weird light shine bright so other weirdos know where to find you. — Jennifer Coolidge",
"I believe in being strong when everything seems to be going wrong. — Audrey Hepburn",
"The secret to my success is that I bit off more than I could chew and chewed as fast as I could. — Paul Hogan",
"Don’t let the noise of others’ opinions drown out your inner voice. — Steve Jobs",
"Life is short, but it is wide. — Rebecca Wells",
"One person can make a difference, and everyone should try. — John F. Kennedy",
"Don’t wait for the stars to align. Reach up and rearrange them the way you want. — Pharrell Williams",
"If you want to be happy, be. — Leo Tolstoy",
"You only pass through this life once, you don’t come back for an encore. — Elvis Presley",
"Be patient. Good things take time. — Lionel Messi",
"Risk something or forever sit with your dreams. — Herb Brooks",
"You can be the moon and still be jealous of the stars. — Gary Allan",
"Make your life a story worth telling. — Adam Levine",
"Don’t downgrade your dream just to fit your reality. — Moira Forbes",
"Leap and the net will appear. — John Burroughs",
"Magic is believing in yourself. — Johann Wolfgang von Goethe",
"Live your life with arms wide open. — Natasha Bedingfield",
"If you’re always trying to be someone else, who’s going to be you? — Dax Shepard",
"I never look back. It distracts from the now. — Edna Mode (The Incredibles)",
"Be you. Do you. For you. — Megan Rapinoe",
"Creativity is intelligence having fun. — Albert Einstein",
"Everything you can imagine is real. — Pablo Picasso",
"Only the gentle are ever really strong. — James Dean",
"Do one thing every day that scares you. — Eleanor Roosevelt",
"It’s your road, and yours alone. Others may walk it with you, but no one can walk it for you. — Rumi",
"Success is falling nine times and getting up ten. — Jon Bon Jovi",
"Nobody built like you, you design yourself. — Jay-Z",
"Don’t let small minds convince you that your dreams are too big. — Anonymous (popularized by Keke Palmer)",
"Push yourself, because no one else is going to do it for you. — Tyra Banks",
"Discipline is choosing between what you want now and what you want most. — Abraham Lincoln",
"It doesn’t matter how slowly you go as long as you don’t stop. — Confucius",
"Be the heroine of your life, not the victim. — Nora Ephron",
"Your value doesn’t decrease based on someone’s inability to see your worth. — Oprah Winfrey",
"You are the sky. Everything else is just the weather. — Pema Chödrön",
"To be irreplaceable one must always be different. — Coco Chanel",
"You can’t do it unless you can imagine it. — George Lucas",
"The sky is not the limit. It’s only the beginning. — Buzz Aldrin",
"Don’t just exist. Live. — Hunter S. Thompson",
"Celebrate what you’ve accomplished, but raise the bar a little higher each time you succeed. — Mia Hamm",
"Be messy and complicated and afraid and show up anyway. — Glennon Doyle",
"Don’t limit your challenges. Challenge your limits. — Jerry Rice",
"Everything happens for you, not to you. — Byron Katie",
"Be so rooted in your own worth that outside opinions mean nothing. — Laverne Cox",
"Success doesn’t come from what you do occasionally. It comes from what you do consistently. — Marie Forleo",
"You can be both a masterpiece and a work in progress at the same time. — Sophia Bush",
"It’s okay to be a glowstick: sometimes you have to break before you shine. — Jadah Sellner",
"Don’t let your fear decide your future. — Shailene Woodley",
"Go the extra mile — it’s never crowded. — Wayne Dyer",
"If opportunity doesn’t knock, build a door. — Milton Berle",
"Stay close to people who feel like sunlight. — Taylor Swift",
"Power’s not given to you. You have to take it. — Beyoncé",
"You didn’t come this far to only come this far. — Tom Brady",
"You will never influence the world by trying to be like it. — Sean Covey",
"You are your best thing. — Toni Morrison",
"It’s what you do in the dark that puts you in the light. — Alex Morgan",
"The path to success is to take massive, determined action. — Tony Robbins",
"You’ll never get bored when you try something new. — Dr. Seuss",
"Live in the moment, and make it beautiful. — Harry Styles",
"It’s not your job to be everything to everyone. — Reese Witherspoon",
"Know your worth. Then add tax. — RuPaul",
"Don’t be the next anybody. Be the first you. — Kacey Musgraves",
"If you obey all the rules, you miss all the fun. — Katharine Hepburn",
"Be yourself, everyone else is taken. — Oscar Wilde",
"The only way to win is to learn faster than anyone else. — Eric Ries",
"Start where you are. Use what you have. Do what you can. — Arthur Ashe",
"You were not born to be subtle. — Rihanna",
"Success is no accident. It’s hard work, perseverance, and love of what you’re doing. — Pelé",
"Live for each second without hesitation. — Elton John",
"Life is short, and it’s up to you to make it sweet. — Sarah Louise Delany",
"Don’t confuse having a career with having a life. — Hillary Clinton",
"Be thankful for what you have; you’ll end up having more. — Oprah Winfrey",
"Do not follow where the path may lead. Go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
"Be kind to yourself and then let your kindness flood the world. — Pema Chödrön",
"You don’t get what you wish for. You get what you work for. — Daniel Milstein",
"You have to do what you dream of doing even while you’re afraid. — Arianna Huffington",
"If you focus on what you left behind, you will never be able to see what lies ahead. — Gusteau (Ratatouille)",
"Don’t let your fears paralyze you. Let them fuel you. — Simone Biles",
"You must never be fearful about what you are doing when it is right. — Rosa Parks",
"I didn't come this far to only come this far. — David Goggins",
"Stay focused, go after your dreams and keep moving toward your goals. — LL Cool J",
"If you’re tired, do it tired. — Jenna Kutcher",
"It’s okay to outgrow people who don’t grow. — Billy Porter",
"The best revenge is massive success. — Frank Sinatra",
"I am not lucky. You know what I am? I am talented. — Simone Biles",
"Fear kills more dreams than failure ever will. — Suzy Kassem",
"You don’t need permission to be powerful. — Zendaya",
"It’s not your job to be likable. It’s your job to be yourself. — Chimamanda Ngozi Adichie",
"Keep your eyes on the prize and don’t look back. — Selena Gomez",
"Sometimes you just have to throw on lip gloss and pretend to be psyched. — Mindy Kaling",
"Your dream doesn’t have an expiration date. — LL Cool J",
"Even if you stumble, you’re still moving forward. — Denzel Washington",
"It takes courage to grow up and become who you really are. — E.E. Cummings",
"You can be scared and brave at the same time. — Brene Brown",
"You can't let perfection be the enemy of progress. — Emma Watson",
"Be somebody who makes everybody feel like a somebody. — Kid President",
"You can’t move forward without saying goodbye to the past. — Taylor Swift",
"If you don’t like the road you’re walking, start paving another one. — Dolly Parton",
"I learned to always take on things I’d never done before. Growth and comfort do not coexist. — Ginni Rometty",
"You can’t be hesitant about who you are. — Viola Davis",
"Don’t be afraid to fail. Be afraid not to try. — Michael Jordan",
"Don’t sit down and wait for the opportunities to come. Get up and make them. — Madam C.J. Walker",
"Be passionate and be involved in what you believe in, and do it as thoroughly and honestly and fearlessly as you can. — Marie Colvin",
"Whatever it is that you think you want to do, and whatever it is that you think stands between you and that, stop making excuses. — Katia Beauchamp",
"I believe in making the impossible possible because there’s no fun in giving up. — Alicia Keys",
"You’ll never find peace of mind until you listen to your heart. — George Michael",
"Done is better than perfect. — Sheryl Sandberg",
"I’m not bossy. I’m the boss. — Beyoncé",
"Be stubborn about your goals and flexible about your methods. — Jake Gyllenhaal",
"It doesn’t matter who you are or where you come from. The ability to triumph begins with you. — Oprah Winfrey",
"You can't be what you can't see. — Marian Wright Edelman",
"You can’t change what’s going on around you until you start changing what’s going on within you. — Justin Baldoni",
"You are more powerful than you know; you are beautiful just as you are. — Melissa Etheridge",
"There is no greater agony than bearing an untold story inside you. — Maya Angelou",
"Take criticism seriously, but not personally. — Hillary Clinton",
"Failure is an important part of your growth and developing resilience. — Michelle Obama",
"Be brave enough to be bad at something new. — Jon Acuff",
"The more you praise and celebrate your life, the more there is in life to celebrate. — Oprah Winfrey",
"You don’t find the happy life. You make it. — Camilla Eyring Kimball",
"People will forget what you said and what you did, but they’ll never forget how you made them feel. — Maya Angelou",
"Live in such a way that if someone spoke badly of you, no one would believe it. — Zig Ziglar",
"Start where you are. Use what you have. Do what you can. — Arthur Ashe",
"You can waste your lives drawing lines. Or you can live your life crossing them. — Shonda Rhimes",
"Be the kind of person your dog thinks you are. — Ricky Gervais",
"Don't wait for the stars to align. Reach up and rearrange them the way you want. — Pharrell Williams",
"Being confident means believing in yourself. — Venus Williams",
"You can’t blend in when you were born to stand out. — R.J. Palacio",
"The people who are crazy enough to think they can change the world are the ones who do. — Rob Siltanen",
"Have enough courage to trust love one more time and always one more time. — Maya Angelou",
"The road to success is always under construction. — Lily Tomlin",
"When you undervalue what you do, the world will undervalue who you are. — Oprah Winfrey",
"I will not let anyone scare me out of my full potential. — Nicki Minaj",
"You have enemies? Good. That means you’ve stood up for something. — Winston Churchill",
"You can’t pour from an empty cup. Take care of yourself first. — Norm Kelly",
"Owning our story and loving ourselves through that process is the bravest thing we’ll ever do. — Brené Brown",
"You define your own life. Don’t let other people write your script. — Oprah Winfrey",
"You are allowed to be both a masterpiece and a work in progress. — Sophia Bush",
"If you don’t risk anything, you risk even more. — Erica Jong",
"You don’t always need a plan. Sometimes you just need to breathe, trust, and see what happens. — Mandy Hale",
"Never dull your shine for somebody else. — Tyra Banks",
"I don’t want other people to decide who I am. I want to decide that for myself. — Emma Watson",
"If you’re presenting yourself with confidence, you can pull off pretty much anything. — Katy Perry",
"Work hard and be nice to people. — Harry Styles",
"I can be changed by what happens to me. But I refuse to be reduced by it. — Maya Angelou",
"Trust your dopeness. — Issa Rae",
"Clarity comes from action, not thought. — Marie Forleo",
"I say if I’m beautiful. I say if I’m strong. You will not determine my story—I will. — Amy Schumer",
"If I stop to kick every barking dog, I’m not going to get where I’m going. — Jackie Joyner-Kersee",
"I have no special talent. I am only passionately curious. — Albert Einstein",
"Find out who you are and do it on purpose. — Dolly Parton",
"Normal is nothing more than a cycle on a washing machine. — Whoopi Goldberg",
"The biggest adventure you can ever take is to live the life of your dreams. — Oprah Winfrey",
"Be fearless in the pursuit of what sets your soul on fire. — Jennifer Lee",
"It’s not your job to be everything to everyone. — Reese Witherspoon",
"The power of one, if fearless and focused, is formidable. — Gloria Macapagal Arroyo",
"Rock bottom became the solid foundation on which I rebuilt my life. — J.K. Rowling",
"Step out of the history that is holding you back. Step into the new story you are willing to create. — Oprah Winfrey",
"I raise up my voice — not so I can shout but so that those without a voice can be heard. — Malala Yousafzai",
"Life is tough, my darling, but so are you. — Stephanie Bennett-Henry",
"When we strive to become better than we are, everything around us becomes better too. — Paulo Coelho",
"You don’t inspire people by being perfect. You inspire them by how you deal with your imperfections. — Kerry Washington",
"Know what sparks the light in you. Then use that light to illuminate the world. — Oprah Winfrey",
"You are enough just as you are. — Meghan Markle",
"Sometimes the bravest and most important thing you can do is just show up. — Brené Brown",
"You can’t play small just because others are uncomfortable with your light. — Tracee Ellis Ross",
"Don’t wait around for other people to be happy for you. Any happiness you get you’ve got to make yourself. — Alice Walker",
"The way to right wrongs is to turn the light of truth upon them. — Ida B. Wells",
"Champions keep playing until they get it right. — Billie Jean King",
"Sometimes you’ve got to be able to listen to yourself and be okay with no one else understanding. — Christopher Barzak",
"Don’t be afraid to speak up for yourself. Keep fighting for your dreams! — Gabby Douglas",
"Whatever your dream is, every extra penny you have needs to be going to that. — Will Smith",
"If you want to be understood, listen. — Jane Fonda",
"Success is getting what you want, happiness is wanting what you get. — Ingrid Bergman",
"You must find the courage to leave the table if respect is no longer being served. — Tene Edwards",
"Act like you have a crown on your head. — Coco Chanel",
"Do not wait for the perfect time and place to enter, for you are already onstage. — Unknown (quoted by Viola Davis)",
"If you want to fly, you have to give up the things that weigh you down. — Oprah Winfrey",
"Keep your eyes on the stars, and your feet on the ground. — Franklin D. Roosevelt",
"Authenticity is the daily practice of letting go of who we think we’re supposed to be. — Brené Brown",
"Step into the discomfort of growth. — Yara Shahidi",
"Don't settle for average. Bring your best to the moment. — Angela Bassett",
"Whatever you do, do it well. — Walt Disney",
"Don’t be like the rest of them, darling. — Coco Chanel",
"When people show you who they are, believe them. — Maya Angelou",
"The most effective way to do it, is to do it. — Amelia Earhart",
"I’m tough, I’m ambitious, and I know exactly what I want. — Madonna",
"You can’t live your life for other people. You’ve got to do what’s right for you. — The Notebook (Nicholas Sparks)",
"Do not go gentle into that good night. — Dylan Thomas (quoted by Robin Williams)",
"Fight for your fairytale. — Lizzo",
"Go confidently in the direction of your dreams. Live the life you have imagined. — Henry David Thoreau",
"You will never win if you never begin. — Helen Rowland",
"Don’t compromise yourself. You’re all you’ve got. — Janis Joplin",
"If you don’t see a clear path for what you want, sometimes you have to make it yourself. — Mindy Kaling",
"Nothing is impossible. The word itself says 'I’m possible!' — Audrey Hepburn",
"Own who you are. — Michelle Obama",
"There's a power in allowing yourself to be known and heard. — Viola Davis",
"I am mine before I am anyone else’s. — Nayyirah Waheed",
"I really think a champion is defined not by their wins but by how they can recover when they fall. — Serena Williams",
"You can be the lead in your own life. — Kerry Washington",
"Done is better than perfect. — Sheryl Sandberg",
"I have never tried to hide the fact that it is my intention to become the best. — Cristiano Ronaldo",
"Be fearless in the face of adversity. — Beyoncé",
"There is nothing more beautiful than someone who goes out of their way to make life beautiful for others. — Mandy Hale",
"Don’t waste a single second. Just move forward as fast as you can, and go for it. — Rebecca Woodcock",
"You were born to make an impact. — Kevin Hart",
"Strive for progress, not perfection. — Dwayne Johnson",
"The best way to gain self-confidence is to do what you are afraid to do. — Swati Sharma",
"Do what you feel in your heart to be right — for you’ll be criticized anyway. — Eleanor Roosevelt",
"Act as if it were impossible to fail. — Dorothea Brande",
"Don’t let anyone tell you who you are. You tell them. — Pink",
"You have to learn to get up from the table when love is no longer being served. — Nina Simone",
"The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
"Never stop believing in yourself. — Chrissy Metz",
"You can’t have a million-dollar dream with a minimum-wage work ethic. — Stephen C. Hogan",
"Be yourself. Everyone else is already taken. — Oscar Wilde",
"Just keep going. Everybody gets better if they keep at it. — Ted Williams",
"You can't wait for inspiration. You have to go after it with a club. — Jack London",
"If you’re not making mistakes, then you’re not making decisions. — Catherine Cook",
"Don’t get bitter, get better. — Aly Raisman",
"I never change. I simply become more myself. — Joyce Carol Oates",
"Remember, no one can make you feel inferior without your consent. — Eleanor Roosevelt",
"You don’t have to hold yourself hostage to who you used to be. — Oprah Winfrey",
"You may not control all the events that happen to you, but you can decide not to be reduced by them. — Maya Angelou",
"Don’t count the days. Make the days count. — Muhammad Ali",
"The harder the struggle, the more glorious the triumph. — Michelle Akers",
"Your story is what you have, what you will always have. It is something to own. — Michelle Obama",
"The best protection any woman can have is courage. — Elizabeth Cady Stanton",
"Make it happen. Shock everyone. — Nicki Minaj",
"Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
"You can never leave footprints that last if you are always walking on tiptoe. — Leymah Gbowee",
"Take your broken heart, make it into art. — Carrie Fisher",
"You have to believe in yourself when no one else does. — Serena Williams",
"Don’t let the negativity given to you by the world disempower you. — Tyler Perry",
"If you obey all the rules, you miss all the fun. — Katharine Hepburn",
"The question isn’t who is going to let me; it’s who is going to stop me. — Ayn Rand",
"Do it scared. Do it messy. Just do it. — Mel Robbins",
"Whatever you are, be a good one. — Abraham Lincoln",
"The most common way people give up their power is by thinking they don’t have any. — Alice Walker",
"Do what you love, and success will follow. Passion is the fuel behind a successful career. — Meg Whitman",
"You don’t have to be great to start, but you have to start to be great. — Zig Ziglar",
"Be the best version of yourself in anything that you do. — Angelina Jolie",
"You may be disappointed if you fail, but you are doomed if you don’t try. — Beverly Sills",
"Even if you are on the right track, you’ll get run over if you just sit there. — Will Rogers",
"Don’t let someone dim your light just because it’s shining in their eyes. — Dwayne Johnson",
"The more you praise and celebrate your life, the more there is in life to celebrate. — Oprah Winfrey",
"You should never be surprised when someone treats you with respect. You should expect it. — Sarah Dessen",
"Everything you’ve ever wanted is on the other side of fear. — George Addair",
"The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
"Power is not given to you. You have to take it. — Beyoncé",
"Just do what works for you, because there will always be someone who thinks differently. — Michelle Obama",
"You were given this life because you are strong enough to live it. — Robin Roberts",
"Live for yourself and don’t ever stop. — Billie Eilish",
"You can’t pour from an empty cup. Take care of yourself first. — Audre Lorde",
"Push yourself, because no one else is going to do it for you. — Tyra Banks",
"Do something today your future self will thank you for. — Sean Patrick Flanery",
"Keep grinding. Stay persistent. Dreams demand hustle. — Drake",
"Turn your pain into power. — 50 Cent",
"You can reinvent yourself as many times as you want. — Lady Gaga",
"Give light and people will find the way. — Ella Baker",
"Be so good they can’t ignore you. — Steve Martin",
"Stars don’t shine because they want to be seen. They shine because they are stars. — Alexander Den Heijer",
"Some women fear the fire. Some women simply become it. — R.H. Sin",
"Believe in yourself and there will come a day when others will have no choice but to believe with you. — Cynthia Kersey",
"The only thing better than singing is more singing. — Ella Fitzgerald",
"I'd rather regret the things I've done than regret the things I haven't done. — Lucille Ball",
"Be fearless in the face of adversity. — Rihanna",
"You can waste your lives drawing lines. Or you can live your life crossing them. — Shonda Rhimes",
"There’s power in looking silly and not caring that you do. — Amy Poehler",
"Work until you no longer have to introduce yourself. — Drake",
"I’m not afraid of failure. I’m afraid of not trying. — Jay-Z",
"The minute you learn to love yourself, you won’t want to be anyone else. — Rihanna",
"Make your life a mission — not an intermission. — Arnold H. Glasow",
"Don’t try to lessen yourself for the world; let the world catch up to you. — Beyoncé",
"You can be terrified and brave at the same time. — Brene Brown",
"I’m not going to limit myself just because people won’t accept the fact that I can do something else. — Dolly Parton",
"You can’t let success get to your head or failure get to your heart. — Will Smith",
"The question I ask myself almost every day is, ‘Am I doing the most important thing I could be doing?’ — Mark Zuckerberg",
"Nobody can give you wiser advice than yourself. — Cicero",
"I do not try to dance better than anyone else. I only try to dance better than myself. — Arianna Huffington",
"Stop shrinking to fit into places you’ve outgrown. — Danielle Doby",
"Don’t wait for opportunity. Create it. — George Bernard Shaw",
"I think in life you should work on yourself until the day you die. — Serena Williams",
"I am deliberate and afraid of nothing. — Audre Lorde",
"Sometimes the smallest step in the right direction ends up being the biggest step of your life. — Naeem Callaway",
"You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
"Being honest may not get you a lot of friends, but it’ll always get you the right ones. — John Lennon",
"You’re not obligated to win. You’re obligated to keep trying. — Maya Angelou",
"I’m not going to continue knocking on that old door that doesn’t open for me. I’m going to create my own door and walk through that. — Ava DuVernay",
"I don’t want other people to decide who I am. I want to decide that for myself. — Emma Watson",
"Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
"Some people feel the rain. Others just get wet. — Bob Marley",
"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. — Oprah Winfrey",
"If you don’t like something, change it. If you can’t change it, change your attitude. — Maya Angelou",
"You’re allowed to scream, you’re allowed to cry, but do not give up. — Unknown (quoted by Halsey)",
"Every strike brings me closer to the next home run. — Babe Ruth",
"Turn your wounds into wisdom. — Oprah Winfrey",
"Be messy and complicated and afraid and show up anyway. — Glennon Doyle",
"It takes courage to grow up and become who you really are. — E.E. Cummings",
"It’s not about how you look, it’s about how you feel. — Billie Eilish",
"Don’t apologize for evolving past other people’s comfort zones. — Erykah Badu",
"You’ve always had the power, my dear. You just had to learn it for yourself. — Glinda (The Wizard of Oz)",
"You can’t move mountains by whispering at them. — Pink",
"When they go low, we go high. — Michelle Obama",
"The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
"If you want to fly, you have to give up the stuff that weighs you down. — Toni Morrison",
"I didn’t get there by wishing for it or hoping for it, but by working for it. — Estée Lauder",
"If you’re not evolving, you’re dying. — Kanye West",
"Failure is just the condiment that gives success its flavor. — Truman Capote",
"Be like snow — beautiful but cold. — Lana Del Rey",
"Ignore the critics. Only mediocrity is safe from ridicule. Dare to be different! — Dita Von Teese",
"It’s not about perfect. It’s about effort. — Jillian Michaels",
"Keep your head up, keep your heart strong. — Ben Howard",
"Never be afraid to sit awhile and think. — Lorraine Hansberry",
"Love yourself. It is important to stay positive because beauty comes from the inside out. — Jenn Proske",
"I’m not built for comfort. I’m built for greatness. — Janelle Monáe",
"Start where you are. Use what you have. Do what you can. — Arthur Ashe",
"You don’t need to be accepted by others. You need to accept yourself. — Thich Nhat Hanh",
"Success is about consistency. — Michelle Obama",
"You were born to stand out. Don’t ever try to fit in. — Emma Stone",
"I am my best work — a series of road maps, reports, recipes, doodles, and prayers from the front lines. — Audre Lorde",
"Be willing to embrace the chaos. — Lady Gaga",
"Life is not about waiting for the storm to pass but about learning to dance in the rain. — Vivian Greene",
"It is not our differences that divide us. It is our inability to recognize, accept, and celebrate those differences. — Audre Lorde",
"Success is nothing more than a few simple disciplines, practiced every day. — Jim Rohn",
"You have to be the change you want to see in the world. — Mahatma Gandhi",
"Don’t just survive. Thrive. — Ariana Grande",
"Respect yourself and others will respect you. — Confucius",
"You can’t blend in when you were born to stand out. — R.J. Palacio",
"Be bold. Be brave. Be you. — Angelina Jolie",
"Never bend your head. Always hold it high. Look the world straight in the face. — Helen Keller",
"You don’t get to choose how you’re going to die, or when. But you can decide how you’re going to live now. — Joan Baez",
"Creativity is contagious. Pass it on. — Albert Einstein",
"Your life is your story. Write well. Edit often. — Drake Bell",
"You can’t use up creativity. The more you use, the more you have. — Maya Angelou",
"The truth will set you free, but first it will piss you off. — Gloria Steinem",
"Don't give it five minutes if you're not going to give it five years. — Meghan Markle",
"You must do the thing you think you cannot do. — Eleanor Roosevelt",
"Don’t dream about success. Get out there and work for it. — Sophia Amoruso",
"Life’s tough, but so are you. — Christina Aguilera",
"You are the author of your own story. If you don’t like where this chapter is going, it’s okay to start a new one. — Unknown (quoted by Zendaya)",
"It is never too late to be what you might have been. — George Eliot",
"There is no greater gift you can give or receive than to honor your calling. — Oprah Winfrey",
"Don’t let anyone rob you of your imagination, your creativity, or your curiosity. — Mae Jemison",
"One good thing about music, when it hits you, you feel no pain. — Bob Marley",
"Trust yourself. You know more than you think you do. — Benjamin Spock",
"You don’t have to be fearless. Just don’t let fear stop you. — Charlie Day",
"I didn’t come this far to only come this far. — Eric Thomas",
"Success doesn’t come from what you do occasionally, it comes from what you do consistently. — Marie Forleo",
"Don’t sit down and wait for the opportunities to come. Get up and make them. — Madam C.J. Walker",
"Find your lane. Make history. — Nipsey Hussle",
"You are your best thing. — Toni Morrison",
"Stay patient and trust your journey. — Kobe Bryant",
"It always seems impossible until it’s done. — Nelson Mandela",
"You have to learn the rules of the game. And then you have to play better than anyone else. — Albert Einstein",
"Don’t downgrade your dream just to fit your reality. — Moira Forbes",
"Know what sparks the light in you. Then use that light to illuminate the world. — Oprah Winfrey",
"Take your dreams seriously. — Lupita Nyong’o",
"You are not a drop in the ocean. You are the entire ocean in a drop. — Rumi",
"I never dreamed of success, I worked for it. — Estée Lauder",
"Start where you are. Use what you have. Do what you can. — Arthur Ashe",
"You must never be fearful about what you are doing when it is right. — Rosa Parks",
"The most courageous act is still to think for yourself. Aloud. — Coco Chanel",
"Even the darkest night will end and the sun will rise. — Victor Hugo",
"Success is most often achieved by those who don’t know that failure is inevitable. — Coco Chanel",
"You become what you believe. — Oprah Winfrey",
"Only those who dare to fail greatly can ever achieve greatly. — Robert F. Kennedy",
"Know your worth, then add tax. — Anonymous (popularized by RuPaul)",
"I say if I’m beautiful. I say if I’m strong. You will not determine my story—I will. — Amy Schumer",
"Some people are old at 18 and some are young at 90. Time is a concept that humans created. — Yoko Ono",
"If you’re not in the arena getting your ass kicked, I’m not interested in your feedback. — Brené Brown",
"Every no brings me closer to a yes. — Mark Cuban",
"Dreams are lovely. But they are just dreams. Fleeting, ephemeral, pretty. But dreams do not come true just because you dream them. — Shonda Rhimes",
"I love the person I’ve become, because I fought to become her. — Kaci Diane",
"Be so aligned with your purpose that nothing can shake your confidence. — Janelle Monáe",
"The best way to make dreams come true is to wake up. — Mae C. Jemison",
"Don’t be afraid to give up the good to go for the great. — John D. Rockefeller",
"You are your best thing. — Toni Morrison",
"Do not let what you cannot do interfere with what you can do. — John Wooden",
"Let your smile change the world but don’t let the world change your smile. — Demi Lovato",
"Some women fear the fire. Some women simply become it. — R.H. Sin",
"Be the kind of leader that you would follow. — Condoleezza Rice",
"If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
"Be yourself. Everyone else is taken. — Oscar Wilde",
"Speak your mind, even if your voice shakes. — Maggie Kuhn",
"Be loyal to your future, not your past. — Mel Robbins",
"Be bold enough to use your voice, brave enough to listen to your heart, and strong enough to live the life you've always imagined. — Anonymous (often used by Lupita Nyong’o)",
"Elegance is when the inside is as beautiful as the outside. — Coco Chanel",
"You are the CEO of your own life. Start acting like it. — Lilly Singh",
"The most beautiful thing you can wear is confidence. — Blake Lively",
"Go after your dreams. All of them. — Issa Rae",
"Your energy introduces you before you even speak. — Jay Shetty",
"If they don’t give you a seat at the table, bring a folding chair. — Shirley Chisholm",
"Don't be afraid to be ambitious about your goals. — Arnold Schwarzenegger",
"I had to make my own living and my own opportunity! Don’t sit down and wait for the opportunities to come. Get up and make them. — Madam C.J. Walker",
"Don't let the world change your smile. Let your smile change the world. — Demi Lovato",
"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. — Maya Angelou",
"Rejection is just redirection. — Keala Settle",
"When something goes wrong in your life, just yell ‘Plot twist!’ and move on. — Stacey London",
"Don't let small minds convince you that your dreams are too big. — Anonymous (often used by Keke Palmer)",
"One child, one teacher, one book, one pen can change the world. — Malala Yousafzai",
"You can be both soft and powerful. — Cleo Wade",
"If you want to be original, be ready to be copied. — Coco Chanel",
"Live out your imagination, not your history. — Stephen Covey",
"Vulnerability is not winning or losing; it’s having the courage to show up. — Brené Brown",
"Don’t adapt to the energy in the room. Influence the energy in the room. — Anonymous (used by Laverne Cox)",
"Success is nothing if you don’t have the right people to share it with. — Beyoncé",
"It’s not about how fast you get there. It’s about not stopping. — Missy Elliott",
"Sometimes courage is the little voice at the end of the day saying I’ll try again tomorrow. — Mary Anne Radmacher",
"You can’t find peace by avoiding life. — Virginia Woolf",
"Be proud of who you are, and not ashamed of how someone else sees you. — Selena Gomez",
"Keep your face to the sunshine and you cannot see the shadows. — Helen Keller",
"The most common way people give up their power is by thinking they don’t have any. — Alice Walker",
"Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
"The best way out is always through. — Robert Frost",
"You are never too small to make a difference. — Greta Thunberg",
"I don't go by the rule book. I lead from the heart, not the head. — Princess Diana",
"Make your life your message. — Mahatma Gandhi",
"When you can’t find someone to follow, be the one to lead. — Roxane Gay",
"The future rewards those who press on. — Barack Obama",
"Be passionate and move forward with gusto every single hour of every single day. — Dwayne Johnson",
"Don’t try to lessen yourself for the world; let the world catch up to you. — Beyoncé",
"I’m not bossy. I’m the boss. — Beyoncé",
"Dream big. Start small. But most of all, start. — Simon Sinek",
"I like to challenge myself. I like to learn — so I like to try new things and try to keep growing. — David Schwimmer",
"Behind every successful woman is herself. — Unknown (used by Reese Witherspoon)",
"The power of visibility can never be underestimated. — Margaret Cho",
"Do what you feel in your heart to be right — for you’ll be criticized anyway. — Eleanor Roosevelt",
"Don't wait for permission to be great. — Pharrell Williams",
"You can’t let your failures define you — you have to let them teach you. — Barack Obama",
"You can have it all. Just not all at once. — Oprah Winfrey",
"You don’t always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens. — Mandy Hale",
"The real difficulty is to overcome how you think about yourself. — Maya Angelou",
"Sometimes the hardest thing and the right thing are the same. — Miley Cyrus",
"It is better to fail in originality than to succeed in imitation. — Herman Melville (quoted by Lady Gaga)",
"Whatever you do, do it with all your heart. — Kevin Hart",
"Life is about using the whole box of crayons. — RuPaul",
"It’s never too late to be what you might have been. — George Eliot",
"Owning our story and loving ourselves through that process is the bravest thing that we’ll ever do. — Brené Brown",
"Don’t let insecurity ruin the beauty you were born with. — Tyra Banks",
"The goal is not to be better than the other man, but your previous self. — The Dalai Lama",
"Just because you are struggling doesn’t mean you are failing. — Demi Lovato",
"The most powerful thing a woman can do is be herself. — Gigi Hadid",
"You can't stop the waves, but you can learn to surf. — Jon Kabat-Zinn",
"You are the sky. Everything else is just the weather. — Pema Chödrön",
"Sometimes you just have to throw on lip gloss and pretend to be psyched. — Mindy Kaling",
"Never apologize for being ambitious. — Charlize Theron",
"Don’t let the bad days make you think you have a bad life. — Lauren Conrad",
"Being realistic is the most commonly traveled road to mediocrity. — Will Smith",
"Confidence is the sexiest thing a woman can have. It’s much sexier than any body part. — Aimee Mullins",
"There's no such thing as failure. Failure is just life trying to move us in another direction. — Oprah Winfrey",
"Real change, enduring change, happens one step at a time. — Ruth Bader Ginsburg",
"If you want something said, ask a man; if you want something done, ask a woman. — Margaret Thatcher",
"The best thing to hold onto in life is each other. — Audrey Hepburn",
"Every day brings a chance to start over. — Mariah Carey",
"The only way you’re going to have success is to have lots of failures first. — Sergey Brin",
"Stay true to yourself. An original is worth more than a copy. — Suzy Kassem",
"You can't be hesitant about who you are. — Viola Davis",
"Hard work keeps the wrinkles out of the mind and spirit. — Helena Rubinstein",
"I don’t like to gamble, but if there’s one thing I’m willing to bet on, it’s myself. — Beyoncé",
"Be the kind of person that makes other people want to up their game. — Mindy Kaling",
"Stop trying to be perfect and just be yourself. — Zendaya",
"There is nothing wrong with being ambitious. — Reese Witherspoon",
"The best way to find yourself is to lose yourself in the service of others. — Mahatma Gandhi",
"It’s time to start living the life you’ve imagined. — Henry James",
"Never let anyone treat you like you’re ordinary. — Anonymous (popularized by Blake Lively)",
"Know your worth and don’t give discounts. — Tyra Banks",
"Don’t wait for opportunities, create them. — Chamillionaire",
"Sometimes you have to be your own hero. — Jennifer Love Hewitt",
"Your playing small does not serve the world. — Marianne Williamson",
"Be willing to fail. Let yourself fail. Fail in the way in which you want to fail. — Philip Seymour Hoffman",
"Success is liking yourself, liking what you do, and liking how you do it. — Maya Angelou",
"Don’t dim your light just because it’s shining in someone else’s eyes. — Unknown (used by Laverne Cox)",
"You don’t need anyone’s permission to be great. — Kanye West",
"I don’t chase dreams, I hunt goals. — Grant Cardone",
"You can’t be brave if you’ve only had wonderful things happen to you. — Mary Tyler Moore",
"Be the person your younger self would be proud of. — Anonymous (popularized by Meghan Markle)",
"Don’t let the behavior of others destroy your inner peace. — Dalai Lama",
"The secret to getting ahead is getting started. — Mark Twain",
"I’ve learned that making a living is not the same thing as making a life. — Maya Angelou",
"You’ll be too much for some people. Those aren’t your people. — Glennon Doyle",
"The best part of beauty is that which no picture can express. — Francis Bacon (used by Natalie Portman)",
"Stars can’t shine without darkness. — D.H. Sidebottom (quoted by Selena Gomez)",
"Don't let anyone rob you of your imagination, your creativity, or your curiosity. — Mae Jemison",
"Don’t let perfection be the enemy of progress. — Winston Churchill",
"You're allowed to be both a masterpiece and a work in progress. — Sophia Bush",
"You don’t owe anyone pretty. — Erin McKean (shared by Florence Welch)",
"The most powerful weapon on earth is the human soul on fire. — Ferdinand Foch (quoted by Oprah)",
"Work hard in silence, let success make the noise. — Frank Ocean",
"Fall in love with becoming the best version of yourself. — Zendaya",
"You either walk inside your story or you stand outside and hustle for your worthiness. — Brené Brown",
"Comparison is the thief of joy. — Theodore Roosevelt",
"Your silence will not protect you. — Audre Lorde",
"Create a life that feels good on the inside, not one that just looks good on the outside. — Unknown (used by Jessica Alba)",
"Real queens fix each other’s crowns. — Gina Carey",
"Confidence is silent. Insecurities are loud. — Rihanna",
"I’m still learning. — Michelangelo (quoted by Maya Angelou)",
"Be unapologetically you. — Serena Williams",
"The cost of not following your heart is spending the rest of your life wishing you had. — J.K. Rowling",
"Be who you needed when you were younger. — Ayesha Siddiqi",
"Don’t let the world make you hard. — Kurt Vonnegut (popular with Demi Lovato)",
"You will never influence the world by trying to be like it. — Sean Covey",
"Nothing will work unless you do. — Maya Angelou",
"You don’t get what you want. You get what you believe. — Oprah Winfrey",
"I am not what happened to me. I am what I choose to become. — Carl Jung (used by Viola Davis)",
"Dreams don’t have deadlines. — LL Cool J",
"You don’t inspire people by being perfect. You inspire them by how you deal with your imperfections. — Kerry Washington",
"You are not required to set yourself on fire to keep others warm. — Penny Reid",
"There is no competition because nobody can be you. — Michaela Coel",
"Risk being seen in all your glory. — Jim Carrey",
"You get in life what you have the courage to ask for. — Oprah Winfrey",
"She remembered who she was and the game changed. — Lalah Delia",
"You are allowed to outgrow people. This includes past versions of yourself. — Megan Jayne Crabbe",
"Energy is contagious. Either you affect people or you infect people. — T.D. Jakes",
"Make sure your worst enemy doesn’t live between your own two ears. — Laird Hamilton",
"I don’t do fashion. I am fashion. — Coco Chanel",
"If you don’t stand for something, you’ll fall for anything. — Malcolm X",
"You’ll never influence the world by trying to be like it. — Unknown (used by Zendaya)",
"If you’re tired, do it tired. — Jen Hatmaker",
"Just keep swimming. — Dory (Ellen DeGeneres)",
"The work you do while you procrastinate is probably the work you should be doing for the rest of your life. — Jessica Hische",
"Be so rooted in your own worth that outside validation becomes irrelevant. — Anonymous (popular with Laverne Cox)",
"I want to grow. I want to be better. You grow. We all grow. We’re made to grow. — Tupac Shakur",
"Don’t downgrade your dream to match your reality. Upgrade your belief to match your vision. — Anonymous (used by Steve Harvey)",
"The ones who are crazy enough to think they can change the world are the ones that do. — Steve Jobs",
"The most important thing is to enjoy your life — to be happy — it’s all that matters. — Audrey Hepburn",
"If you don’t bet on yourself, no one else will. — Kevin Hart",
"Success is doing ordinary things extraordinarily well. — Jim Rohn",
"Power is not given to you. You have to take it. — Beyoncé",
"Your value doesn’t decrease based on someone’s inability to see your worth. — Emma Watson",
"Do not fear failure but rather fear not trying. — Roy T. Bennett",
"Live for yourself and no one else. — Billie Eilish",
"You are magic. Don’t ever apologize for the fire in you. — Anonymous (used by Halsey)",
"You’re not behind. You’re exactly where you need to be. — Mel Robbins",
"The secret of getting ahead is getting started. — Agatha Christie (attributed by Reese Witherspoon)",
"You were given this life because you are strong enough to live it. — Robin Roberts",
"Keep moving forward. That’s the only way to live. — Walt Disney",
"Even miracles take a little time. — The Fairy Godmother (Cinderella)",
"Everything you want is on the other side of consistency. — John Maxwell",
"The world needs your voice. — Lin-Manuel Miranda",
"Make your life a masterpiece. — Tony Robbins",
"You are not lost. You are redirecting. — Anonymous (shared by Lizzo)",
"You can’t pour from an empty cup. Fill yourself first. — Norm Kelly",
"Don’t tell people your plans. Show them your results. — Ryan Reynolds",
"Take the risk or lose the chance. — Chris Pratt",
"Strength grows in the moments when you think you can’t go on but you keep going anyway. — Venus Williams",
"I don't chase dreams. I breathe life into them. — Viola Davis",
"I’m not afraid of storms, for I’m learning how to sail my ship. — Louisa May Alcott",
"You can't use up creativity. The more you use, the more you have. — Maya Angelou",
"Don’t let the fear of what could happen make nothing happen. — Steve Harvey",
"Bet on yourself. You’ll always be your best investment. — Tabitha Brown",
"Failure is not the opposite of success. It’s part of it. — Arianna Huffington",
"You were born to be real, not perfect. — Demi Lovato",
"Put blinders on and go full speed ahead. — Liza Minnelli",
"Just because you fail once doesn't mean you're gonna fail at everything. — Marilyn Monroe",
"Don’t let anyone ever dull your sparkle. — Paris Hilton",
"Let your passion be your purpose. — Oprah Winfrey",
"You can’t start the next chapter if you keep re-reading the last one. — Michael McMillan",
"I will not have my life narrowed down. I will not bow down to somebody else's whim or to someone else's ignorance. — Bell Hooks",
"Stop shrinking to fit places you’ve outgrown. — Oprah Winfrey",
"I’m a movement by myself, but I’m a force when we’re together. — Ne-Yo",
"The road to success is always under construction. — Lily Tomlin",
"I believe in pink. — Audrey Hepburn",
"It’s better to be absolutely ridiculous than absolutely boring. — Marilyn Monroe",
"Success isn’t about how much money you make. It’s about the difference you make in people’s lives. — Michelle Obama",
"The reward for conformity is that everyone likes you but yourself. — Rita Mae Brown",
"If you want to go fast, go alone. If you want to go far, go together. — African Proverb",
"I’m interested in women’s health because I’m a woman. I’d be a darn fool not to be on my own side. — Maya Angelou",
"Believe in your flyness, conquer your shyness. — Kanye West",
"Let them see you sweat. — Angela Bassett",
"You don't make progress by standing on the sidelines. — Shirley Chisholm",
"I’m always trying to turn my negative into a positive. — Cardi B",
"I’ve never been one to stay still. I’ve always wanted to grow. — Jennifer Lopez",
"I’ve had to learn to fight all my life – got to learn to keep smiling. If you smile things will work out. — Serena Williams",
"You are the one that possesses the keys to your being. You carry the passport to your own happiness. — Diane von Furstenberg",
"I have standards I don't plan on lowering for anybody... including myself. — Zendaya",
"I don't want the fear of failure to stop me from doing what I really care about. — Emma Watson",
"You don’t need to compete with anyone but yourself. — Zendaya",
"Be the kind of woman that makes other women want to up their game. — Beyoncé",
"I will not stay silent so that you can stay comfortable. — Laverne Cox",
"Don’t let them tame you. — Isadora Duncan",
"You are allowed to be both a masterpiece and a work in progress simultaneously. — Sophia Bush",
"Don't be afraid to fail big, to dream big. — Denzel Washington",
"You don’t have to play masculine to be a strong woman. — Mary Elizabeth Winstead",
"Be the best version of yourself, not the second-best version of someone else. — Judy Garland",
"Don’t wait for the right opportunity. Create it. — George Bernard Shaw",
"You don’t become what you want, you become what you believe. — Oprah Winfrey",
"Don't be like the rest of them, darling. — Coco Chanel",
"Let your light shine so brightly that others can see their way out of the dark. — Katrina Mayer",
"A woman with a voice is, by definition, a strong woman. — Melinda Gates",
"Some people never go crazy. What truly horrible lives they must lead. — Charles Bukowski",
"You have to know what sparks the light in you so that you, in your own way, can illuminate the world. — Oprah Winfrey",
"Don’t let anyone’s ignorance, hate, drama, or negativity stop you from being the best person you can be. — Anonymous (popular with Lizzo)",
"You are more than enough. — Jameela Jamil",
"Confidence is not 'they will like me.' Confidence is 'I'll be fine if they don't.' — Christina Grimmie",
"You cannot be really first-rate at your work if your work is all you are. — Anna Quindlen",
"Don’t ever make decisions based on fear. Make decisions based on hope and possibility. — Michelle Obama",
"Think big and don’t listen to people who tell you it can’t be done. — Tim Ferriss",
"Sometimes it's the princess who kills the dragon and saves the prince. — Samuel Lowe (quoted by Emilia Clarke)",
"Live your life like you're 80 years old looking back on your teenage years. — Taylor Swift",
"You're not the opinion of someone who doesn't know you. — Taylor Swift",
"The most revolutionary thing a woman can do is love herself. — Gabrielle Union",
"Success is a series of small wins. — Julianne Hough",
"The best way to gain confidence is to do things you are scared of. — Demi Lovato",
"It’s really liberating to not pretend to be someone else. — Reese Witherspoon",
"People will stare. Make it worth their while. — Harry Winston",
"Keep your eyes on the stars, and your feet on the ground. — Franklin D. Roosevelt",
"I know what I bring to the table. So trust me when I say I’m not afraid to eat alone. — Unknown (used by Tiffany Haddish)",
"I'd rather be hated for who I am than loved for who I am not. — Kurt Cobain",
"Authenticity is magnetic. — Unknown (popular in Hollywood circles)",
"Don't confuse being busy with being productive. — Marie Forleo",
"The most powerful words in the universe are the words you say to yourself. — Marie Forleo",
"There is no force more powerful than a woman determined to rise. — W.E.B. Dubois (attributed often to BossBabe)",
"Just keep showing up. — Brené Brown",
"The goal is to die with memories, not dreams. — Anonymous (used by Jaden Smith)",
"Trust your journey, even when you don’t understand it. — Demi Lovato",
"One day you’ll look back and be glad you didn’t give up. — Anonymous (used by Nick Jonas)",
"Success doesn’t come from what you do occasionally, it comes from what you do consistently. — Marie Forleo",
"Don’t fear failure. Fear being in the exact same place next year. — Unknown (used by Issa Rae)",
"If you stumble, make it part of the dance. — Cheryl Burke",
"If it’s both terrifying and amazing, then you should definitely pursue it. — Erada",
"You are allowed to take up space. — Florence Welch",
"I’ve never been afraid to be different. — Billie Eilish",
"You’ve got to learn to leave the table when love’s no longer being served. — Nina Simone",
"Confidence is armor. You just have to put it on. — Priyanka Chopra",
"You’re only given a little spark of madness. You mustn’t lose it. — Robin Williams",
"You don’t need a title to be a leader. — Mark Cuban",
"If you don’t risk anything, you risk even more. — Erica Jong",
"Embrace what makes you different. — Priyanka Chopra",
"You can’t do epic stuff with basic people. — Anonymous (used by Rihanna)",
"There’s nothing wrong with you. There’s a lot wrong with the world you live in. — Chris Colfer",
"It’s okay to be both soft and strong. — Unknown (used by Halsey)",
"Be willing to be a beginner every single morning. — Meister Eckhart (quoted by Demi Moore)",
"You're going to be happy, said life, but first I’ll make you strong. — Paolo Coelho",
"Know this: you can start over, each morning. — Tyler Joseph",
"The comeback is always stronger than the setback. — Unknown (popularized by Lizzo)",
"Work hard, stay humble, and make it happen. — Gigi Hadid",
"You don’t have to shine for anyone but yourself. — Kristen Stewart",
"You're allowed to be both a work of art and a work in progress. — Sophia Bush",
"The real flex is healing. — Jada Pinkett Smith",
"Kindness is always fashionable. — Amelia Barr (popular in fashion)",
"Be the story you want to tell. — Anonymous (used by Reese Witherspoon)",
"Take up space. Own your power. — Elaine Welteroth",
"You were born to disrupt the status quo. — Ava DuVernay",
"The energy you give is the energy you get. — Jhené Aiko",
"Don't just stand for the success of other women — insist on it. — Gail Blanke",
"Don’t forget how wildly capable you are. — Halsey",
"Success is being able to look back at your life and say, I did it my way. — Frank Sinatra",
"Protect your peace. — Jada Pinkett Smith",
"Be louder than your insecurities. — Unknown (used by Zendaya)",
"The life in front of you is far more important than the life behind you. — Joel Osteen",
"You can’t do it all. And you don’t have to. — Cameron Diaz",
"Be fearless in the pursuit of what sets your soul on fire. — Jennifer Lee",
"The future belongs to those who prepare for it today. — Malcolm X",
"I didn’t come here to be average. — Michael B. Jordan",
"Own your story. — Viola Davis",
"You define beauty for yourself. — Zendaya",
"The best thing you can possibly do with your life is to tackle the motherf***ing shit out of it. — Cheryl Strayed",
"Love yourself first, because that’s who you’ll be spending the rest of your life with. — Tyra Banks",
"I don’t believe in luck. I believe in preparation. — Bobby Knight",
"Keep evolving. — Pharrell Williams",
"I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
"The way I see it, if you want the rainbow, you gotta put up with the rain. — Dolly Parton",
"To love oneself is the beginning of a lifelong romance. — Oscar Wilde",
"Refuse to be average. Let your heart soar as high as it will. — A.W. Tozer (used by Michelle Williams)",
"The world will see you the way you see you, and treat you the way you treat yourself. — Beyoncé",
"I know for sure that what we dwell on is who we become. — Oprah Winfrey",
"You have to be unique, and different, and shine in your own way. — Lady Gaga",
"Above all, be the heroine of your life, not the victim. — Nora Ephron",
"Clarity trumps certainty. — Robin Sharma",
"You can’t keep dancing with the devil and wonder why you're still in hell. — Unknown (popularized by Demi Lovato)",
"The real glow-up is becoming comfortable in your own skin. — Lizzo",
"Let your hustle be louder than your mouth. — Anonymous (used by Cardi B)",
"Being underestimated is the biggest advantage you can have. — Kevin Hart",
"Make your life your art. — Solange Knowles",
"You can’t heal in the same environment that made you sick. — Unknown (quoted by Selena Gomez)",
"You weren’t born to fit in. You were born to stand out. — Lady Gaga",
"Take up space. — Elaine Welteroth",
"Don't fear your fire. Use it. — Halsey",
"I don't want to make money. I want to make a difference. — Lady Gaga",
"Be a first-rate version of yourself, not a second-rate version of someone else. — Judy Garland",
"You don't have to be loud to be powerful. — Alexandria Ocasio-Cortez",
"You have to be odd to be number one. — Dr. Seuss",
"The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey",
"Discomfort is the price of admission to a meaningful life. — Susan David",
"Done is better than perfect. — Sheryl Sandberg",
"Be real. Be honest. Be you. — Taylor Swift",
"The only way to do it is to do it. — Amelia Earhart",
"There’s nothing wrong with being a work in progress. — Sophia Bush",
"Do your thing and don’t care if they like it. — Tina Fey",
"Never settle for anything less than your best. — Serena Williams",
"Decide what kind of life you really want… and then say no to everything that isn’t that. — Brianna Wiest",
"Keep going. That’s it. That’s the mantra. — Jennifer Lewis",
"Let your dreams be bigger than your fears. — Khloé Kardashian",
"If you don't build your dream, someone will hire you to help build theirs. — Tony Gaskins",
"Be unapologetic about your goals. — Issa Rae",
"Don’t get it twisted: confidence is quiet. Insecurity is loud. — Janelle Monáe",
"Make yourself so happy that others become happy just by looking at you. — Yoko Ono",
"You have to be willing to look ridiculous. — Tina Fey",
"You don’t have to explain your vibe. It speaks for itself. — Jhené Aiko",
"Turn your pain into your power. — Taraji P. Henson",
"Wake up and slay. — Cardi B",
"Never be ashamed of your story. It will inspire others. — Demi Lovato",
"You are a powerful force. Stop pretending like you’re not. — Tracee Ellis Ross",
"Be so aligned with who you are that nothing can shake your foundation. — Yara Shahidi",
"Your vibe attracts your tribe. — Jennifer Aniston",
"Let people underestimate you. That’s your superpower. — Keke Palmer",
"Soft is strong. — Camila Cabello",
"You don’t need to have it all figured out to keep going. — Emma Stone",
"Your authenticity is your superpower. — Hunter Schafer",
"I refuse to be anything other than myself. — Billie Eilish",
"Choose yourself. Every single time. — Lizzo",
"Live boldly. Push boundaries. Don’t apologize. — Zendaya",
"If you're lucky enough to be different, don't ever change. — Taylor Swift",
"Strong back, soft front, wild heart. — Brené Brown",
"I’m not fearless. I’m brave. There’s a difference. — Jennifer Lawrence",
"The most powerful thing you can do is be yourself. — Jane Fonda",
"Success isn’t about money, it’s about freedom. — Morgan Freeman",
"You don’t have to be the loudest in the room to be heard. — Natalie Portman",
"The world needs your fire, not your perfection. — Glennon Doyle",
"Let your weird light shine bright. — Jenny Lawson",
"Don’t fit in when you were born to stand out. — Matshona Dhliwayo",
"Confidence is the best outfit. Rock it and own it. — Blake Lively",
"You can't spell legendary without 'legit'. — RuPaul",
"Choose courage over comfort. — Brené Brown",
"It’s your story. Feel free to hit them with a plot twist. — Ava DuVernay",
"You’re more than enough. — Halsey",
"Don’t be afraid of being seen trying. — Kevin Hart",
"Glow through what you go through. — Anonymous (used by Zendaya)",
"Sometimes growth feels like breaking. — Jada Pinkett Smith",
"Be the vibe you want to experience. — Jhené Aiko",
"Take up space. You were never meant to be small. — Yara Shahidi",
"You're not too much. They just weren't ready for all of you. — Laverne Cox",
"You don't need to be fixed. You're not broken. — Demi Lovato",
"Stay weird. Stay different. — Graham Moore (Oscars speech)",
"Live loud. Love harder. Shine brighter. — Lady Gaga",
"Your feelings are valid. Don’t let anyone tell you otherwise. — Selena Gomez",
"If they think your dreams are too big, show them how small their vision is. — Rihanna",
"Walk like you own the world, even if you rent it. — Anonymous (used by Lizzo)",
"You are not behind. You are exactly where you are supposed to be. — Mel Robbins",
"You’re not lost. You’re recalibrating. — Reese Witherspoon",
"You deserve to take up space in every room you walk into. — Mindy Kaling",
"You're the magic you've been waiting for. — Jameela Jamil",
"If they underestimate you, let them. Then surprise them. — Jennifer Hudson",
"Your future self will thank you for showing up today. — Serena Williams",
"Your best is always enough. — Oprah Winfrey",
];
function getRandomQuote() {
  const index = Math.floor(Math.random() * quotes.length);
  return quotes[index];
}

function displayQuote() {
  quoteElement.classList.remove("show");

  // Wait for fade-out to complete (600ms = same as CSS)
  setTimeout(() => {
    quoteElement.textContent = getRandomQuote();

    // Allow browser a tiny bit of time before fade-in
    setTimeout(() => {
      quoteElement.classList.add("show");
    }, 20);
  }, 600);
}


// Add fade class and first quote on page load
window.addEventListener("load", () => {
  quoteElement.classList.add("fade");
  displayQuote();
});

// Change quote on button click
newQuoteButton.addEventListener("click", displayQuote);


